# Generated by Django 4.1.6 on 2023-02-26 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ME', 'Main Event'), ('CM', 'Co-Main Event'), ('CP', 'Card Principal'), ('CPM', 'Card Preliminar')], max_length=50, verbose_name='Card')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Evento')),
                ('data', models.DateField(verbose_name='Data')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='Luta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bolao.card', verbose_name='Card')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bolao.evento', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'luta',
                'verbose_name_plural': 'lutas',
            },
        ),
        migrations.CreateModel(
            name='Lutador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=50, verbose_name='Sobrenome')),
                ('apelido', models.CharField(max_length=50, verbose_name='Apelido')),
            ],
            options={
                'verbose_name': 'lutador',
                'verbose_name_plural': 'lutadores',
            },
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('UD', 'Decisão Unânime'), ('SD', 'Decisão Dividida'), ('MD', 'Decisão Majoritária'), ('KO', 'Nocaute'), ('TKO', 'Nocaute Técnico'), ('SUB', 'Finalização'), ('NC', 'No Contest'), ('EMP', 'Empate')], max_length=50, verbose_name='Método')),
                ('round', models.PositiveSmallIntegerField(verbose_name='Round')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bolao.evento', verbose_name='Evento')),
                ('luta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bolao.luta', verbose_name='Luta')),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bolao.lutador', verbose_name='Resultado')),
            ],
            options={
                'verbose_name': 'resultado',
                'verbose_name_plural': 'resultados',
            },
        ),
        migrations.AddField(
            model_name='luta',
            name='lutadorA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lutador', to='bolao.lutador', verbose_name='Lutador 1'),
        ),
        migrations.AddField(
            model_name='luta',
            name='lutadorB',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oponente', to='bolao.lutador', verbose_name='Lutador 2'),
        ),
    ]
