# Generated by Django 4.1.6 on 2023-02-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lutador',
            name='apelido',
            field=models.CharField(blank=True, max_length=50, verbose_name='Apelido'),
        ),
    ]
